//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class anh
    {
        public int id_image { get; set; }
        public string link { get; set; }
        public string mo_ta { get; set; }
        public Nullable<int> id_post { get; set; }
    
        public virtual post post { get; set; }
    }
}
