//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chat
    {
        public int id_chat { get; set; }
        public string noi_dung { get; set; }
        public string uid { get; set; }
        public string nguoi_nhan { get; set; }
        public System.DateTime time { get; set; }
    
        public virtual user user { get; set; }
    }
}
