//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tnut_socialEntities : DbContext
    {
        public tnut_socialEntities()
            : base("name=tnut_socialEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> account { get; set; }
        public virtual DbSet<anh> anh { get; set; }
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<comment> comment { get; set; }
        public virtual DbSet<chat> chat { get; set; }
        public virtual DbSet<group> group { get; set; }
        public virtual DbSet<khoa> khoa { get; set; }
        public virtual DbSet<like> like { get; set; }
        public virtual DbSet<lop> lop { get; set; }
        public virtual DbSet<mon_hoc> mon_hoc { get; set; }
        public virtual DbSet<nganh> nganh { get; set; }
        public virtual DbSet<post> post { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tai_lieu> tai_lieu { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<user_group> user_group { get; set; }
    }
}
